name = "nuaborges-admin"
pages_build_output_dir = "out-admin"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "NUA_CONTENT"
id = "ec3771fcaf4946a69c5c2b3d5563341a"

[[kv_namespaces]]
binding = "NUA_MEDIA"
id = "978b3cb264224d159bd05e283a9208ad"
