-- Cloudflare D1 Migration: Scientific KB with FTS5 Full-Text Search
CREATE TABLE IF NOT EXISTS kb_chunks (
  id TEXT PRIMARY KEY,
  source_id TEXT,
  domain TEXT,
  authority TEXT,
  tier TEXT,
  title TEXT,
  summary_pt TEXT,
  content TEXT,
  citation TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE VIRTUAL TABLE IF NOT EXISTS kb_chunks_fts USING fts5(
  title, summary_pt, content, keywords,
  content="kb_chunks",
  content_rowid="rowid"
);

-- Inserção em Lote dos Chunks
INSERT OR REPLACE INTO kb_chunks (id, source_id, domain, authority, tier, title, summary_pt, content, citation) VALUES ('chk_who_def_sexual_health', 'src_who_sexual_health', 'sexual_health', 'WHO / OMS', 'A', 'Definição Oficial de Saúde Sexual pela OMS', 'A OMS define saúde sexual não apenas como a ausência de doenças ou disfunções, mas como um estado de bem-estar físico, emocional, mental e social em relação à sexualidade, exigindo respeito, experiências prazerosas, seguras e livres de coerção.', 'A saúde sexual é um estado de bem-estar físico, emocional, mental e social em relação à sexualidade; não é meramente a ausência de doença, disfunção ou enfermidade. A saúde sexual requer uma abordagem positiva e respeitosa da sexualidade e das relações sexuais, bem como a possibilidade de ter experiências sexuais prazerosas e seguras, livres de coerção, discriminação e violência. Para que a saúde sexual seja alcançada e mantida, os direitos sexuais de todas as pessoas devem ser respeitados, protegidos e cumpridos.', 'ORGANIZAÇÃO MUNDIAL DA SAÚDE (OMS). Defining sexual health: report of a technical consultation on sexual health. Genebra: WHO, 2006.');
INSERT OR REPLACE INTO kb_chunks (id, source_id, domain, authority, tier, title, summary_pt, content, citation) VALUES ('chk_basson_desejo_responsivo', 'src_basson_model', 'sexology', 'Rosemary Basson (2000)', 'B', 'Modelo Circular de Resposta Sexual e Desejo Responsivo (Basson)', 'Rosemary Basson demonstrou que a resposta sexual feminina frequentemente opera em ciclo não linear: o desejo pode ser ''responsivo'' (despertado a partir da estimulação e intimidade prévia) e não necessariamente espontâneo, despatologizando mulheres que não sentem desejo do nada.', 'No modelo circular de Basson (2000), a mulher pode iniciar o encontro sexual a partir de um estado de neutralidade sexual, motivada por intimidade afetiva, conexão ou cumplicidade. A partir de estímulos eróticos adequados e receptividade, a excitação subjetiva se instala, gerando subsequentemente o desejo sexual responsivo. Isso contrasta com o modelo linear tradicional de Masters & Johnson/Kaplan, que pressupunha o desejo espontâneo como pré-requisito obrigatório para qualquer ato sexual.', 'BASSON, R. The Female Sexual Response: A Different Model. Journal of Sex & Marital Therapy, v. 26, n. 1, p. 51-65, 2000. PMID: 10693529.');
INSERT OR REPLACE INTO kb_chunks (id, source_id, domain, authority, tier, title, summary_pt, content, citation) VALUES ('chk_clitoris_anatomia_prazer', 'src_febrasgo_disfuncoes', 'anatomy', 'FEBRASGO / Sexologia Clínica', 'B', 'Complexo Anatômico do Clitóris e Prazer Feminino', 'O clitóris é o único órgão humano cuja função exclusiva é o prazer. É uma estrutura tridimensional de 9 a 11 cm com mais de 8.000 terminações nervosas na glande, e cerca de 70% a 80% das mulheres necessitam de estimulação clitoriana direta ou indireta para atingir o orgasmo.', 'Anatomicamente, o clitóris é um complexo erétil formado por glande externa, corpo, duas cruras (pernas) e dois bulbos vestibulares que abraçam o canal vaginal. Estudos de ressonância e ultrassonografia funcional demonstram que o chamado ''orgasmo vaginal'' é, na verdade, resultado da estimulação indireta das raízes internas e bulbos do clitóris pela parede anterior da vagina (complexo clitoureterovaginal). A estimulação clitoriana direta ou combinada é a via fisiológica primária de orgasmo para a maioria absoluta das mulheres.', 'FEDERAÇÃO BRASILEIRA DAS ASSOCIAÇÕES DE GINECOLOGIA E OBSTETRÍCIA (FEBRASGO). Manual de Orientação em Sexologia Clínica. Rio de Janeiro: FEBRASGO, 2021.');
INSERT OR REPLACE INTO kb_chunks (id, source_id, domain, authority, tier, title, summary_pt, content, citation) VALUES ('chk_prevencao_combinada_prep_pep', 'src_ms_prevencao_combinada', 'sexual_health', 'Ministério da Saúde do Brasil', 'A', 'Mandala da Prevenção Combinada e Profilaxias (PrEP e PEP)', 'A Prevenção Combinada une diferentes métodos biomédicos, comportamentais e estruturais: preservativos externos e internos, testagem regular, imunização (HPV e Hepatite B), PEP (até 72h após exposição) e PrEP (uso programado contínuo ou sob demanda).', 'A abordagem da Prevenção Combinada do Ministério da Saúde supera o foco exclusivo no preservativo, integrando intervenções biomédicas: 1) Preservativos masculinos e femininos com gel lubrificante à base de água ou silicone; 2) PrEP (Profilaxia Pré-Exposição): ingestão de antirretrovirais para prevenir a infecção pelo HIV antes de contatos de risco; 3) PEP (Profilaxia Pós-Exposição): urgência médica com antirretrovirais iniciados em até 72 horas após situação de risco (relação desprotegida, rompimento de preservativo ou violência sexual) durante 28 dias; 4) Conceito I=I (Indetectável = Intransmissível): pessoas vivendo com HIV com carga viral indetectável há pelo menos 6 meses não transmitem o vírus por via sexual.', 'BRASIL. Ministério da Saúde. Protocolo Clínico e Diretrizes Terapêuticas para Profilaxia Pré-Exposição (PrEP) de Risco à Infecção pelo HIV. Brasília: Ministério da Saúde, 2022.');
INSERT OR REPLACE INTO kb_chunks (id, source_id, domain, authority, tier, title, summary_pt, content, citation) VALUES ('chk_consentimento_modelo_fries', 'src_unesco_itse', 'consent', 'UNESCO / Educação Sexual Integral', 'A', 'Princípios do Consentimento Sexual Ativo e Informado (FRIES)', 'O consentimento sexual deve ser FRIES: Freely given (livre de pressão/álcool/coerção), Reversible (reversível a qualquer instante), Informed (com conhecimento claro do que vai acontecer), Enthusiastic (desejado mutuamente) e Specific (válido apenas para aquela prática específica).', 'O consentimento não é a mera ausência de um ''não'', mas a presença ativa, contínua e explícita de um ''sim'' mútuo e consciente. O modelo internacionalmente aceito define: 1) Livremente concedido: sem ameaças, chantagem emocional, culpa ou sob incapacidade por substâncias; 2) Reversível: qualquer pessoa pode mudar de ideia e interromper o ato a qualquer segundo; 3) Informado: ambas as partes conhecem exatamente o que acontecerá e quais proteções estão sendo usadas; 4) Entusiasta: há vontade genuína de participar; 5) Específico: concordar com carícias ou beijos não implica consentimento para sexo oral ou penetração.', 'UNESCO. International technical guidance on sexuality education: an evidence-informed approach. Paris: UNESCO Publishing, 2018.');