import { SiteContent } from './types';

export const DEFAULT_SITE_CONTENT: SiteContent = {
  seo: {
    title: 'Nua Borges — Plataforma Oficial',
    description:
      'Educadora sexual e sexóloga em formação. Um olhar íntimo, sofisticado e sem rodeios sobre o desejo, a autoimagem e a liberdade feminina.',
    canonicalUrl: 'https://nuaborges.phstatic.com.br',
    ogImage: '/images/nua/hero/hero-1.jpg',
  },
  header: {
    brandName: 'Nua Borges',
    brandMonogram: 'NB',
    navLogoStyle: 'monogram',
    showInstagram: true,
    showOnlyFans: true,
    onlyFansText: 'OnlyFans',
    onlyFansUrl: 'https://onlyfans.com/nuaborges',
  },
  hero: {
    eyebrow: 'PLATAFORMA OFICIAL',
    title: 'Nua Borges',
    tagline: 'Onde o corpo é arte e o prazer é livre de culpas.',
    description:
      'Um olhar íntimo, sofisticado e sem rodeios sobre o desejo, a autoimagem e a liberdade feminina.',
    ctaText: 'Acessar Acervo Exclusivo',
    ctaUrl: 'https://onlyfans.com/nuaborges',
    fullVerticalPhoto: true,
    cinematicCoverLayout: true,
    photos: [
      {
        id: 'hero-1',
        title: 'Nua Borges',
        session: '01',
        imageUrl: '/images/nua/hero/hero-1.jpg',
      },
      {
        id: 'hero-2',
        title: 'Nua Borges',
        session: '02',
        imageUrl: '/images/nua/hero/hero-2.jpg',
      },
      {
        id: 'hero-3',
        title: 'Nua Borges',
        session: '03',
        imageUrl: '/images/nua/gallery/gallery-1.png',
      },
      {
        id: 'hero-4',
        title: 'Nua Borges',
        session: '04',
        imageUrl: '/images/nua/gallery/gallery-2.png',
      },
    ],
  },
  gallery: {
    eyebrow: 'GALERIA DE ENSAIOS',
    title: 'Acervo Autoral',
    subtitle:
      'Produções independentes sob luz natural, revelando a estética e a verdade do corpo.',
    photos: [
      {
        id: 'gal-1',
        title: 'Luz & Silhueta',
        caption: 'Estudo autoral sobre contorno e naturalidade',
        imageUrl: '/images/nua/gallery/gallery-1.png',
        linkUrl: 'https://onlyfans.com/nuaborges',
        active: true,
      },
      {
        id: 'gal-2',
        title: 'Sombras Íntimas',
        caption: 'Linhas do corpo sob a penumbra suave',
        imageUrl: '/images/nua/gallery/gallery-2.png',
        linkUrl: 'https://onlyfans.com/nuaborges',
        active: true,
      },
      {
        id: 'gal-3',
        title: 'Pele & Textura',
        caption: 'Composição minimalista e toque',
        imageUrl: '/images/nua/gallery/gallery-3.png',
        linkUrl: 'https://onlyfans.com/nuaborges',
        active: true,
      },
      {
        id: 'gal-4',
        title: 'Presença & Olhar',
        caption: 'Sensualidade desarmada e presença autêntica',
        imageUrl: '/images/nua/gallery/gallery-4.png',
        linkUrl: 'https://onlyfans.com/nuaborges',
        active: true,
      },
    ],
  },
  about: {
    eyebrow: 'MANIFESTO & BIOGRAFIA',
    headline: 'A coragem de despir a vergonha.',
    role: 'Educadora Sexual & Sexóloga em Formação',
    pullQuote:
      'A vergonha é a primeira fronteira que nos impõem. Meu trabalho é ajudar a derrubá-la.',
    paragraph1:
      'Meu trabalho nasce do encontro entre a ciência da sexologia e a expressão fotográfica autoral. Acredito na desmistificação do prazer como ferramenta de autoconhecimento e dignidade.',
    paragraph2:
      'Aqui compartilho reflexões profundas sobre corpo, relações e intimidade com acolhimento, verdade e sem nenhum tabu.',
    signature: 'Deixa de vergonha ♡',
    photoUrl: '/images/nua/about/about.jpg',
  },
  channels: {
    eyebrow: 'CANAIS OFICIAIS',
    title: 'Presença & Conexão',
    subtitle:
      'Acompanhe a pesquisa, os diálogos sobre sexologia e os ensaios autorais exclusivos.',
    onlyfans: {
      title: 'OnlyFans',
      badge: 'ACERVO EXCLUSIVO',
      description:
        'Acesso aos ensaios fotográficos completos em alta resolução, vídeos e produções autorais sem censura.',
      tags: ['Ensaios Completos', 'Sem Censura', 'Produção Autoral'],
      buttonText: 'ACESSAR ACERVO EXCLUSIVO',
      url: 'https://onlyfans.com/nuaborges',
    },
    instagram: {
      title: 'Instagram',
      handle: '@nuaborges',
      description:
        'Reflexões diárias sobre corpo, relações, liberdade e desmistificação do prazer sem rodeios.',
      tags: ['Educação Sexual', 'Corpo & Tabus', 'Rotina & Bastidores'],
      buttonText: 'ACOMPANHAR NO INSTAGRAM',
      url: 'https://www.instagram.com/nuaborges',
    },
    contactBanner: {
      title: 'Assessoria, Imprensa & Parcerias Comerciais',
      description:
        'Atendimento direto para marcas, entrevistas, colaborações e propostas.',
      buttonText: 'Iniciar Contato Comercial →',
    },
  },
  contact: {
    modalTitle: 'Assessoria & Contato',
    modalSubtitle: 'Propostas comerciais, imprensa, palestras e colaborações.',
    officialEmail: 'contato@nuaborges.phstatic.com.br',
    subjects: [
      'Parceria Comercial / Publicidade',
      'Imprensa / Entrevista',
      'Dúvidas & Acesso Exclusivo',
      'Outro Assunto',
    ],
  },
  footer: {
    brandName: 'Nua Borges',
    role: 'Educadora Sexual & Sexóloga em Formação',
    concept: 'Corpo, relações e liberdade.',
    copyrightText: 'Nua Borges. Todos os direitos reservados.',
    signOff: 'Deixa de vergonha ♡',
  },
  institutional: {
    sectionTitle: 'Institucional',
    description: 'Diretrizes legais, proteção de dados e transparência editorial.',
    links: [
      {
        id: 'link-termos',
        name: 'Termos de Uso',
        label: 'Termos de Uso',
        description: 'Condições gerais, direitos autorais e proteção da obra artística.',
        url: '/termos',
        iconName: 'scale',
        active: true,
        order: 1,
        openInNewTab: false,
      },
      {
        id: 'link-privacidade',
        name: 'Política de Privacidade',
        label: 'Política de Privacidade',
        description: 'Privacidade, discrição e conformidade com a LGPD.',
        url: '/privacidade',
        iconName: 'shield',
        active: true,
        order: 2,
        openInNewTab: false,
      },
    ],
  },
  library: [
    {
      id: 'lib-1',
      name: 'Hero — Retrato Primário',
      url: '/images/nua/hero/hero-1.jpg',
      uploadedAt: 'Oficial',
      favorite: true,
      albumIds: ['album-retratos', 'album-profissionais'],
      usedIn: ['Hero'],
    },
    {
      id: 'lib-2',
      name: 'Hero — Retrato Secundário',
      url: '/images/nua/hero/hero-2.jpg',
      uploadedAt: 'Oficial',
      favorite: false,
      albumIds: ['album-retratos'],
      usedIn: ['Hero'],
    },
    {
      id: 'lib-3',
      name: 'Sobre Mim — Retrato Autoral',
      url: '/images/nua/about/about.jpg',
      uploadedAt: 'Oficial',
      favorite: true,
      albumIds: ['album-retratos', 'album-profissionais'],
      usedIn: ['Sobre Mim'],
    },
    {
      id: 'lib-4',
      name: 'Galeria — Luz & Silhueta',
      url: '/images/nua/gallery/gallery-1.png',
      uploadedAt: 'Oficial',
      favorite: true,
      albumIds: ['album-ensaios', 'album-profissionais'],
      usedIn: ['Galeria'],
    },
    {
      id: 'lib-5',
      name: 'Galeria — Sombras Íntimas',
      url: '/images/nua/gallery/gallery-2.png',
      uploadedAt: 'Oficial',
      favorite: false,
      albumIds: ['album-ensaios'],
      usedIn: ['Galeria'],
    },
    {
      id: 'lib-6',
      name: 'Galeria — Pele & Textura',
      url: '/images/nua/gallery/gallery-3.png',
      uploadedAt: 'Oficial',
      favorite: false,
      albumIds: ['album-ensaios'],
      usedIn: ['Galeria'],
    },
    {
      id: 'lib-7',
      name: 'Galeria — Presença & Olhar',
      url: '/images/nua/gallery/gallery-4.png',
      uploadedAt: 'Oficial',
      favorite: true,
      albumIds: ['album-ensaios'],
      usedIn: ['Galeria'],
    },
  ],
  albums: [
    {
      id: 'album-ensaios',
      name: 'Ensaios Principais',
      description: 'Acervo de ensaios com iluminação natural e estética autoral.',
      coverMediaId: 'lib-4',
      coverUrl: '/images/nua/gallery/gallery-1.png',
      mediaIds: ['lib-4', 'lib-5', 'lib-6', 'lib-7'],
      createdAt: '2026-09-01',
    },
    {
      id: 'album-retratos',
      name: 'Retratos & Capa',
      description: 'Fotos em alta resolução selecionadas para capa e biografia.',
      coverMediaId: 'lib-1',
      coverUrl: '/images/nua/hero/hero-1.jpg',
      mediaIds: ['lib-1', 'lib-2', 'lib-3'],
      createdAt: '2026-09-10',
    },
    {
      id: 'album-profissionais',
      name: 'Fotos Profissionais',
      description: 'Seleção para divulgação, imprensa e assessoria comercial.',
      coverMediaId: 'lib-3',
      coverUrl: '/images/nua/about/about.jpg',
      mediaIds: ['lib-1', 'lib-3', 'lib-4'],
      createdAt: '2026-09-15',
    },
  ],
};
